# Generated by Django 3.0.2 on 2020-02-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=90)),
                ('receiver_name', models.CharField(max_length=90)),
                ('bucket_name', models.CharField(max_length=90)),
                ('sender_email', models.CharField(max_length=90)),
                ('receiver_email', models.CharField(max_length=90)),
                ('shared_filename', models.CharField(max_length=90)),
                ('real_filename', models.CharField(max_length=90)),
            ],
        ),
    ]
